

#### GLM

# STIMA UN MODELLO LINEARE DOVE LE VARIABILI INDIPENDENTI SONO DI TIPO QUALITATIVO
## POSSO UTILIZZARLO SIA PER CONTEGGI CHE PER VARIABILI DI TIPO CONTINUO
# EQUIVALENTE DELL'ANALISI DELLA VARIANZA CON POISSON

counts <- c(18,17,15,20,10,20,25,13,12) #VETTORE
outcome <- gl(3,1,9) #FATTORE
treatment <- gl(3,3) # FATTORE
print(d.AD <- data.frame(treatment, outcome, counts))
# SICCOME SONO CONTEGGI FACCIO RIFERIMENTO ALLA POISSON
#

glm.D93 <- glm(counts ~ outcome + treatment, family = poisson())
anova(glm.D93)
summary(glm.D93)
# ABBIAMO UNA MODELLIZZAZIONE DI TIPO CORNER POINT, OUTCOME=1, TREAT MENT=0
# ESSENDO LA POISSON AVRò UNA STATISTICA TEST Z CHE è SEMPRE IL COEFF/DEV.STND, LA DISTRIBUIZIONE DI
# RIFERIMENTO PER IL TEST NON è PIù LA T MA IN QUESTO CASO è LA NORMALE
# IL TEST . HO=0 H1=DIVERSO DA 0, IL TEST è SUL COEFFICIENTE, DISTINGUERE TRA DOMANDA 
# CHE è DIETRO IL TEST è STATISTICA TEST.

# NELLA MODELLIZZAZIONE CORNER POINT LE STIME SONO LE VARIAZIONI RISPETTO AL CORNER POIN
# L'OUTCOMè 

# IL FATTORE OUTCOME è INFLUENTE SUL VALORE MEDIO MENTRE TREATMENT NO 









